version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceRentableItemsPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceRentableItemsPlugin.Integration.Test"
  schedule:
    interval: daily