dist: xenial
language: csharp
solution: ServiceTrashInspectionPlugin.sln
mono: none
dotnet: 3.1.101
addons:
  chrome: stable
  mariadb: '10.5'
script:
  - echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list
  - wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rabbitmq-server
  - sudo systemctl enable rabbitmq-server
  - sudo systemctl start rabbitmq-server
  - sudo rabbitmqctl add_user admin password
  - sudo rabbitmqctl set_user_tags admin administrator
  - sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_management
  - wget http://localhost:15672/cli/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - ./rabbitmqadmin declare queue name=eformsdk-input durable=true
  - ./rabbitmqadmin declare queue name=eform-service-rentableitem-plugin durable=true
  - dotnet build ServiceRentableItemsPlugin.sln
  - dotnet test -v n ServiceRentableItemsPlugin.Integration.Test/ServiceRentableItemsPlugin.Integration.Test.csproj
